### ISSUE TITLE
New background images

### ISSUE THREAD

**Issue by Michael-YIPPEE** [AnthisCareerAcademy/PM-Matching-Game#19]
the spider background is not acceptable.

**Comment by Michael-YIPPEE** [comment]
![bloosmoil](https://github.com/user-attachments/assets/3e66da0d-913f-43f0-9b4a-d73316a073a8)

**Comment by YaseenK24** [comment]
![LEGO_logo svg](https://github.com/user-attachments/assets/ee005a1d-9cf3-4fc1-b71d-5f72595309ba)

**Comment by YaseenK24** [comment]
![Jordan](https://github.com/user-attachments/assets/9ad3c00c-7d24-4c57-9939-4e1f686069de)

**Comment by YaseenK24** [comment]
![Raising_Cane's_Chicken_Fingers_logo svg](https://github.com/user-attachments/assets/fac1050a-b44d-4e50-9589-cace9ca87b87)
